### ISSUE TITLE
无法读取cookies属性?

### ISSUE THREAD

**Issue by MuenYu** [VegetableCat/qqzone#1]
**已安装requests**

cookie
```
LW_uid=H1m572n3R4W3s8V2Y7W325K8n0; eas_sid=W1V5x24384u388C2h7L3N6c2V4; pgv_pvid=6725774804; pgv_pvid_new=_d5e7462ff2; pgv_pvi=4186823680; RK=yWJFmHVgVj; ptcz=9de73c107b03d009701b021ddc4df83dbd21d570cb4ed83db7f5f85331a256b6; QZ_FE_WEBP_SUPPORT=1; __Q_w_s_hat_seed=1; o_cookie=********; ue_ts=1524065814; ue_uk=481fbde45a805beb7ba1eb5a15347750; ue_uid=350948dbd3d6269a46113949becfbf5b; ue_skey=a79380918a58eaa80feb003184d53179; LW_pid=e87377e66c4f22d0244758b0fff3d6fa; pac_uid=1_490184577; pgv_si=s2040642560; LW_sid=K1K5i2O4O4B6m5l7S1U6v9O0w3; pgv_info=pgvReferrer=http://qt.qq.com/zhibo/index.html&ssid=s3039235392; ptisp=cnc; Loading=Yes; _qpsvr_localtk=0.6947670737875113; ptui_loginuin=********; pt2gguin=o*******; uin=o*****; skey=@LBm2p28ri; p_uin=o*******; pt4_token=p5NsnCRVG2wgWfWVrWIFIMOHx-g9308UzmTONu5UQEo_; __Q_w_s__QZN_TodoMsgCnt=1; cpu_performance_v8=65
```

error
```
Traceback (most recent call last):
  File "secret.py", line 190, in <module>
    main()
  File "secret.py", line 182, in main
    t = secretSpider(t,f,cookies)
  File "secret.py", line 62, in secretSpider
    p['g_tk'] = getOldGTK(cookies['p_skey'])
KeyError: 'p_skey'
```

**Comment by MuenYu** [comment]
我是使用chrome运行`document.write(document.cookie)`得到的cookie，如果直接写地址栏会跳转搜索。。但这应该是一个原理吧？

刚刚又重新获取了一次，仍然没看见`p_skey`参数

**Comment by MuenYu** [comment]
那也就是说这个爬虫已经失效了，对吗？

在此，非常感谢您的解答
